# Generated by Django 5.0.1 on 2024-02-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='myapp.color'),
        ),
    ]
