# Generated by Django 5.0.1 on 2024-02-29 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_color_products_product_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_amount', models.CharField(max_length=50)),
                ('price_increment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stoage_options', to='myapp.product')),
            ],
        ),
    ]
