# Generated by Django 5.0.1 on 2024-03-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_product_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storageoption',
            name='price_increment',
        ),
        migrations.AddField(
            model_name='storageoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
