# Generated by Django 5.0.1 on 2024-03-01 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_storageoption_price_increment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_colors/')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_products', to='myapp.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='myapp.product')),
            ],
        ),
    ]
