# Generated by Django 5.0.1 on 2024-03-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_productcolorimage_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands_logos/')),
            ],
        ),
    ]
