# Generated by Django 5.0.1 on 2024-03-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_phonebrand_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
