# Generated by Django 5.0.1 on 2024-03-05 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_phonebrand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebrand',
            name='image',
        ),
        migrations.RemoveField(
            model_name='phonebrand',
            name='model',
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='myapp.phonebrand')),
            ],
        ),
    ]
