# Generated by Django 5.0.1 on 2024-03-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
