# Generated by Django 5.0.1 on 2024-04-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_accessories_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolorimage',
            name='color',
        ),
        migrations.AddField(
            model_name='productcolorimage',
            name='color_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
