# Generated by Django 5.2 on 2025-04-30 05:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_product_price_id_product_stripe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('reason', models.CharField(choices=[('purchase', 'Customer Purchase'), ('restock', 'Restock'), ('adjustment', 'Inventory Adjustment'), ('return', 'Customer Return'), ('reservation', 'Reservation'), ('release', 'Reservation Release')], default='adjustment', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('session_id', models.CharField(default='', max_length=255)),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='Default', max_length=100)),
                ('color_image', models.ImageField(blank=True, null=True, upload_to='variants/')),
                ('storage', models.CharField(default='64GB', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=99.99, max_digits=10)),
                ('count_in_stock', models.IntegerField(default=0)),
                ('reserved_stock', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=100, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productcolorimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='storageoption',
            name='product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='accessories',
            options={'verbose_name_plural': 'Accessories'},
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phonebrand',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='countInStock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='repairservice',
            name='service_type',
        ),
        migrations.AddField(
            model_name='accessories',
            name='count_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accessories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phonebrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AddField(
            model_name='phonebrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='num_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='repairservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repairservice',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='repairservice',
            name='name',
            field=models.CharField(default='Default Service', max_length=200),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='brand',
            field=models.CharField(default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='name',
            field=models.CharField(default='Default Accessory', max_length=200),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='price',
            field=models.DecimalField(decimal_places=2, default=49.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='phonebrand',
            name='name',
            field=models.CharField(default='Default Brand', max_length=100),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='name',
            field=models.CharField(default='Default Model', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Default Product', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('phone', 'Phone'), ('accessory', 'Accessory'), ('other', 'Other')], default='phone', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='repairservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=10),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='myapp.product'),
        ),
        migrations.AddField(
            model_name='inventoryreservation',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='myapp.productvariant'),
        ),
        migrations.AddField(
            model_name='inventorychange',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_changes', to='myapp.productvariant'),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ProductColorImage',
        ),
        migrations.DeleteModel(
            name='StorageOption',
        ),
    ]
