# Generated by Django 5.2 on 2025-05-04 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_accessories_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='max_purchase_quantity',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='brand',
            field=models.CharField(default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='name',
            field=models.CharField(default='Accessory', max_length=200),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, default='temp-session', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Customer Purchase'), ('restock', 'Restock'), ('adjustment', 'Inventory Adjustment'), ('return', 'Customer Return'), ('reservation', 'Reservation'), ('release', 'Reservation Release')], default='adjustment', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_changes', to='myapp.productvariant'),
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='session_id',
            field=models.CharField(default='temp-session', max_length=255),
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='myapp.productvariant'),
        ),
        migrations.AlterField(
            model_name='phonebrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='phonebrand',
            name='name',
            field=models.CharField(default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='phonebrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='myapp.phonebrand'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='name',
            field=models.CharField(default='Generic Model', max_length=100),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Generic', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Category', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Product', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(default='Black', max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color_image',
            field=models.ImageField(blank=True, null=True, upload_to='variants/'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='myapp.product'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='storage',
            field=models.CharField(default='64GB', max_length=50),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='repairservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repairservice',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='repairservice',
            name='name',
            field=models.CharField(default='Screen Repair', max_length=200),
        ),
        migrations.AlterField(
            model_name='repairservice',
            name='phone_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_services', to='myapp.phonemodel'),
        ),
        migrations.AlterField(
            model_name='repairservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address_line2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
