# Generated by Django 5.2 on 2025-05-26 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_fix_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('data', models.TextField()),
                ('processed_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='inventorychange',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='inventorychange',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorychange',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='image',
            field=models.ImageField(null=True, upload_to='accessories/'),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accessories',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventorychange',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Customer Purchase'), ('restock', 'Restock'), ('adjustment', 'Inventory Adjustment'), ('return', 'Customer Return'), ('reservation', 'Reservation'), ('release', 'Reservation Release')], max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='expires_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inventoryreservation',
            name='session_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phonebrand',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='max_purchase_quantity',
            field=models.PositiveIntegerField(default=10, help_text='Maximum quantity a customer can purchase in a single order'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='storage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='repairservice',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='repairservice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'storage')},
        ),
    ]
