import './globals.css';
import { Inter } from 'next/font/google';
import { CartProvider } from "../app/cart/CartContext"; 

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Zain Wireless',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
